image: ghcr.io/cirruslabs/macos-sonoma-xcode:15.1

stages:
  - CompilePackageOSX
  - CompilePackageMobile

before_script:
  - export LANG=en_US.UTF-8
  - uname -a
  - brew install xcbeautify

CompilePackageMobile:
  tags:
    - xcode
  only:
    variables:
    - $CI_PIPELINE_SOURCE == "web"
    - $CI_COMMIT_REF_NAME == "main"
  stage: CompilePackageMobile
  artifacts:
    name: Kimis.ipa
    paths:
      - Kimis.ipa
  script:
    - Resource/Script/compile.release.mobile.ci.sh

CompilePackageOSX:
  tags:
    - xcode
  only:
    variables:
    - $CI_PIPELINE_SOURCE == "web"
    - $CI_COMMIT_REF_NAME == "main"
  stage: CompilePackageOSX
  artifacts:
    name: Kimis.app
    paths:
      - Kimis.app
  script:
    - Resource/Script/compile.release.macOS.ci.sh
