url: http://127.0.0.1:3555/
port: 3555

db:
  host: postgres
  port: 5432
  db: misskey
  user: misskey
  pass: misskey_api_test_stub_password

redis:
  host: redis
  port: 6379
  pass: misskey_api_test_stub_password

id: 'ulid'
signToActivityPubGet: false
outgoingAddressFamily: dual
