version: '3'

# misskey test env, please include database when commit
services:
  misskey:
    image: misskey/misskey
    restart: always
    volumes:
      - ./config:/misskey/.config/
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    ports:
      - 3555:3555

  postgres:
    image: postgres:15.2 # latest
    restart: always
    environment:
      POSTGRES_PASSWORD: misskey_api_test_stub_password
      POSTGRES_USER: misskey
      POSTGRES_DB: misskey
    volumes:
      - ./payload/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass misskey_api_test_stub_password
    environment:
      - REDIS_PASSWORD=misskey_api_test_stub_password
    volumes:
      - ./payload/redis/data:/data

