name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "4 5 * * *"

jobs:
  test:
    runs-on: macos-14
    steps:
      - name: Setup Orbstack
        run: |
          brew install orbstack
          orbctl start

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Test
        run: |
          Resource/ApiTest/main.sh
