name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "4 5 * * *"

jobs:
  test:
    runs-on: macos-13
    steps:
      - name: switch Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: setup-docker
        uses: docker-practice/actions-setup-docker@master

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Test
        run: |
          Resource/ApiTest/main.sh
